#!/bin/sh

Usage() {
cat <<EOF
   ___________ _   ____
  / ____|__  // | / / /
 / /     /_ </  |/ / /
/ /___ ___/ / /|  / /___
\____//____/_/ |_/_____/ Imperial College London

hpcSubmit 1.4 (July 2019)
n.bourke@imperial.ac.uk, gregory.scott99@imperial.ac.uk

Usage: hpcSubmit <commands.txt> <walltime> <ncpus> <memory>
e.g. hpcSubmit.sh commands.txt 01:00:00 1 8Gb

Executes each line of a text file as separate tasks in a PBSPRO array job.
This job submission textfile can be created by echoing a command to a file.
e.g.
echo " someCommand -optional_flag -input -output " >> job.txt

+-------------------------------------+
| Rough guide to resource allocation: |
|                                     |
| Light Job    01:00:00 1 3Gb         |
| Medium Job   12:00:00 1 8Gb         |
| Heavy Job    24:00:00 1 8Gb         |
| V.heavy Job  48:00:00 1 8Gb         |
+-------------------------------------+

Other tips:
- Max walltime is 72:00:00.
- Greater resources (memory, number of CPUs) will delay the start of your jobs
- Most neuroimaging software will not go above 8Gb of memory. If thinking of going above this, check that it is actually required.
- Can your process use more than 1 CPU? If it can and and it automatically spawns but you dont ask for >1, your job will be killed. If it doesnt, dont increase this number as it will also slow job allocation.
- BEST PRACTICE: Run job on a single subject and view the output log for what the average CPU and Mem usage was. With this check the job sizing guide for the Imperial HPC

EOF
exit 1
}

if [  $# -lt 4 ];
  then
  Usage
  exit 1
fi

if [ $# -eq 4 ];
  then
  input=$1
  walltime=$2
  ncpus=$3
  mem=$4

  echo "input is = $input"
  line=$(head -n 1 $input)
  echo "Walltime = $walltime"
  echo "Number of CPUs = $ncpus"
  echo "Memory = $mem"
fi

dateFunction(){
	date
}

  # Get number of jobs from command file
  NUMJOBS=`wc -l < $input`;

  # Add in condition to capture a single job submission
  if [  "$NUMJOBS" -eq 1 ];
    then
      pbsfile=`mktemp`
      echo "#!/bin/sh" > $pbsfile;
      echo "#PBS -l walltime=$walltime" >> $pbsfile;
      echo "#PBS -l select=1:ncpus=$ncpus:mem=$mem" >> $pbsfile;
      echo "#PBS -j oe" >> $pbsfile;
      echo $line >> $pbsfile;

      echo "WARNING: only one job submitted!"
      echo "Check this correct"
#     echo "PBS file = "
#     echo ${pbsfile}
	echo "Job submitted: $(dateFunction)"
      qsub ${pbsfile}

    else

      # Make place for output logs
      path="$(dirname ${input})" # remove filename
      ex=$(echo ${input} | rev | cut -d/ -f1 | rev); dir=$(cut -d. -f1 <<<$ex) # reverse $input and remove the last field and reverse again

        # Setup pbs submission file and execute it
        pbsfile=`mktemp`;
        outfile=${pbsfile##*/}
        echo "#!/bin/sh" > $pbsfile;
        echo "#PBS -N ${dir}" >> $pbsfile;
        echo "#PBS -l walltime=${walltime}" >> $pbsfile;
        echo "#PBS -l select=1:ncpus=${ncpus}:mem=${mem}" >> $pbsfile;
        echo "#PBS -j oe" >> $pbsfile;
        echo "#PBS -J 1-${NUMJOBS}" >> $pbsfile;
        echo "cmd=\`sed \"\${PBS_ARRAY_INDEX}q;d\" ${input}\`" >> $pbsfile;
        echo "PATH=${PATH}:`pwd`" >> $pbsfile;
        echo "eval \${cmd}" >> $pbsfile;

        echo "Array jobs submitted: $NUMJOBS"
#        echo "PBS file = "
#        echo ${pbsfile}
	echo "Job submitted: $(dateFunction)"
        qsub -k oe ${pbsfile}

  fi

