---
title: "Population data cleaning"
output: html_notebook
date: "15/04/2021"
---

QC population data
1. Merge demographics
2. Filter z-scores

### Clear workspace
```{r, Formating options}
# ---- setup ----
rm(list= ls()) # clear screen
options(scipen=999) # gets rid of scientific notation

# Load packages
pacman::p_load(RColorBrewer, ggsci, tidyverse, readxl, psych, plyr,lme4, lmerTest, MASS, car, emmeans, ggpubr, RNOmni, Cairo, corrr)

## Formating options ##
# show_col(pal_npg("nrc")(10))
myPalette <- c("#3399FF","#FF0000")
fillPalette <- (scale_fill_npg()) # (scale_fill_rickandmorty())
colPalette <- (scale_color_npg()) # (scale_color_rickandmorty())
npgGroupPalette <- c("#4DBBD5FF","#E64B35FF")
npgAgentPalette <- c("#00A087FF","#3C5488FF")

# The errorbars overlapped, so use position_dodge to move them horizontally
pd <- position_dodge(0.1) # move them .05 to the left and right 
ebSize <- 1
fpSize <- 2
pointSize <- 3

# Font type & size
textOption <- element_text(family="Times", size = 22)
facetText  <- element_text( size = 20) #family="Times",

```

# Load population data
```{r}

# Demographics
demographics.raw <- read_csv("~/Google Drive/Imperial/Paeds/analysis/beta/pVolume/data/pop/populationDemographics.csv") 
#imSubj.df <- read_csv("~/Google Drive/Imperial/Paeds/analysis/beta/pVolume/data/pop/imSubj.csv") 
#imSubj.df <- read_csv("~/Google Drive/Imperial/Paeds/analysis/beta/pVolume/data/pop/imSubj.csv") 
imSubj.df <- read_csv("~/Google Drive/Imperial/Paeds/analysis/arc2020/brainAge/imSubj.csv") 
demo.df <- merge(demographics.raw, imSubj.df, by = "subject")


# SPM estimates of volume
vol.df <- read_csv("~/Google Drive/Imperial/Paeds/analysis/arc2020/brainAge/volumes.csv") 

# White and grey matter volume from fsl (population masks)
volume.df <- read_xlsx("~/Google Drive/Imperial/Paeds/tmp_QC/QC.xlsx",
                          sheet = "pop",
                          col_names = TRUE) 

```

# Filtering data based on visualisation and QC 
- remove site UM
- theshold age at 8
```{r}

## Filtering data based on visualisation and QC
df1 <- merge(demo.df, volume.df, by = "subject")
df2 <- merge(df1, vol.df, by = "ID")
df <- df2[ which(df2$site!='UM_1' & df2$ageMonths > 95),] # age filtering here redundent 

n=length(df$subject.x)
for(i in 1:n) {
  df$spm.TICV[i] <- (df$gm_vol[i] + df$wm_vol[i] + df$csf_vol[i])
  df$gm.ratio[i] <- (df$gm[i]/df$spm.TICV[i]) # GM gm_vol
  df$wm.ratio[i] <- (df$wm[i]/df$spm.TICV[i]) # WM wm_vol
  df$ageYears[i] <- df$ageMonths[i]/12
  df$ageFactor[i] <- round(df$ageMonths[i]/12)
}


#Calculate Mean and SD of FA accross tracts for control group
wm.z <- df %>%
  dplyr::select(ID, ageFactor, wm.ratio)   %>%
  mutate(ageFactor = factor(ageFactor))

subsets <-  split(wm.z, wm.z$ageFactor)
subsets <- lapply(subsets, function(s) { s$wm.ratio <- scale(s$wm.ratio); s} )
wm.result <- data.frame()
for(s in subsets) wm.result <- rbind(wm.result, s)
plot(wm.result$ageFactor, wm.result$wm.ratio)
#table(df.z$ageFactor)

gm.z <- df %>%
  dplyr::select(ID, ageFactor, gm.ratio)   %>%
  mutate(ageFactor = factor(ageFactor))

subsets <-  split(gm.z, gm.z$ageFactor)
subsets <- lapply(subsets, function(s) { s$gm.ratio <- scale(s$gm.ratio); s} )
gm.result <- data.frame()
for(s in subsets) gm.result <- rbind(gm.result, s)
plot(gm.result$ageFactor, gm.result$gm.ratio)

volQC <- merge(wm.result, gm.result, by = "ID")
volQC <- volQC %>% 
        dplyr::rename(age = ageFactor.x) %>% 
        dplyr::rename(wm.z = wm.ratio) %>%
        dplyr::rename(gm.z = gm.ratio) %>%
        dplyr::select (.,-c(ageFactor.y)) # Drop the columns of the dataframe

vol.outliers <- volQC[which(volQC$wm.z >= 3.0 | volQC$gm.z >= 3.0 | volQC$wm.z <= -3.0 | volQC$gm.z <= -3.0), ]
vol.clean2.5 <- volQC[which(volQC$wm.z < 2.5 & volQC$gm.z < 2.5 & volQC$wm.z > -2.5 & volQC$gm.z > -2.5), ]
vol.clean3.0 <- volQC[which(volQC$wm.z < 3.0 & volQC$gm.z < 3.0 & volQC$wm.z > -3.0 & volQC$gm.z > -3.0), ]

df.clean <- merge(vol.clean3.0, df, by.x = "ID")
table(df.clean$age)
write.csv(df.clean, "~/Google Drive/Imperial/Paeds/tmp_QC/population_volume.csv")
```

```{r}

table(demo.df$sex)
summary(df$ageMonths)
table(df$sample)

```


## Plot sex data uncorrected for ICV
```{r}
p1 <-  ggplot(data = df.clean, aes(x = ageMonths , y = wm, colour = sex)) +
        geom_point(method = "loses") + 
        geom_smooth() +
        colPalette +
        labs(x = "Age (months)", y = "White matter volume (mm3)", caption="*Not corrected for ICV\nn = 644") +
        theme(text = facetText, legend.text = facetText)
p1

p2 <-  ggplot(data = df.clean, aes(x = ageMonths , y = gm, colour = sex)) +
        geom_point() + 
        geom_smooth(method = "loess") +
        colPalette +
        labs(x = "Age (months)", y = "Grey matter volume (units)", caption="*Not corrected for ICV\nn = 1,314") +
        theme(text = facetText, legend.text = facetText)
p2
```
## Plot data corrected for ICV
```{r}

#df$Age.months <- as.numeric(df$Age.months)
p1 <-  ggplot(data = df.clean, aes(x = ageYears , y = wm.ratio, colour = sample)) +
        geom_point(method = "loses") + 
        geom_smooth() +
        colPalette +
        labs(x = "Age (Years)", y = "White matter volume (ratio)", caption="*corrected for ICV\nn = 1,314") +
        theme(text = facetText, legend.text = facetText)
p1

p2 <-  ggplot(data = df.clean, aes(x = ageYears , y = gm.ratio, colour = sample)) +
        geom_point() + 
        geom_quantile() +
        #geom_smooth(method = "loess") +
        colPalette +
        labs(x = "Age (Years)", y = "Grey matter volume (units)", caption="*corrected for ICV\nn = 1,314") +
        theme(text = facetText, legend.text = facetText)
p2


p3 <-  ggplot(data = df.clean, aes(x = ageYears , y = gm.ratio, colour = sample)) +
        geom_point() + 
        #geom_quantile() +
        geom_smooth(method = "loess") +
        stat_smooth(method="lm", se=TRUE, fill=NA,
                 formula=y ~ poly(x, 3, raw=TRUE))  +    # colour="red"  
        colPalette +
        labs(x = "Age (Years)", y = "Grey matter volume (units)", caption="*corrected for ICV\nn = 1,314") +
        theme(text = facetText, legend.text = facetText)
p3


```


# Change between 8-20
```{r}

a8 <- df.clean[which(df.clean$age=="8"),]
a20 <- df.clean[which(df.clean$age=="20"),]

mean.GM.A8 <- mean(a8$gm.ratio)
mean.GM.A20 <- mean(a20$gm.ratio)

mean.GM.A8/mean.GM.A20*100

mean.WM.A8 <- mean(a8$wm.ratio)
mean.WM.A20 <- mean(a20$wm.ratio)
mean.WM.A20/mean.WM.A8*100

```

# The independent R2 values explaining volume
```{r}

#GM 
m1 <- lm(gm.ratio ~ sample*age*sex, data = df.clean) # *sex did not contribte after TICV
m2 <- lm(gm.ratio ~ age, data = df.clean)
m3 <- lm(gm.ratio ~ sample, data = df.clean)
m4 <- lm(gm.ratio ~ sex, data = df.clean)

summary(m1)
summary(m2)
summary(m3)
summary(m4)
anova(m1, m3)
# Site has larger effect than sample ~17% compared to 3%

#WM 
m1 <- lm(wm.ratio ~ sample*age*sex, data = df.clean) # *sex did not contribte after TICV
m2 <- lm(wm.ratio ~ age, data = df.clean)
m3 <- lm(wm.ratio ~ sample, data = df.clean) # *sex did not contribte
m4 <- lm(wm.ratio ~ sex, data = df.clean)

summary(m1)
summary(m2)
summary(m3)
summary(m4)
anova(m1, m3)


m1 <- lm(gm.ratio ~ site*age, data = df.clean) # *sex did not contribte after TICV
summary(m1)
m2 <- lm(gm.ratio ~ age, data = df.clean)
summary(m2)
m3 <- lm(gm.ratio ~ site, data = df.clean)
summary(m3)

```



# load Imperial data
```{r message=FALSE}

# Test data
neuroimaging.tbi <- read_xlsx("~/Google Drive/Imperial/Paeds/analysis/arc2020/df/neuroimaging_master.xlsx",
                            sheet = "patients",
                            col_names = TRUE) 

neuroimaging.controls <- read_xlsx("~/Google Drive/Imperial/Paeds/analysis/arc2020/df/neuroimaging_master.xlsx",
                            sheet = "controls",
                            col_names = TRUE) 

Imperial.demo.df <- read_xlsx("~/Google Drive/Imperial/Paeds/analysis/arc2020/df/neuroimaging_master.xlsx",
                            sheet = "demo",
                            col_names = TRUE) 

# Imperial.tbi <- read_csv("~/Google Drive/Imperial/Paeds/analysis/arc2020/df/Imperial-volume-mm3.csv")
# 
# # Recoding control that was discovered as a patient (imaging data encoded as "PTBI116", Demographics as "PTBI042")
# Imperial.tbi$Participant[Imperial.tbi$Participant=="PTBI116"] <- "PTBI042"
# # Correcting encoding inconsistancies 
# Imperial.tbi$Participant[Imperial.tbi$Participant=="PTBi004"] <- "PTBI004"
# Imperial.tbi$Participant[Imperial.tbi$Participant=="PTBi103"] <- "PTBI103"
# Imperial.tbi$Participant[Imperial.tbi$Participant=="PITB010"] <- "PTBI010"

# # Test data
 neuroimaging.tbi <- read_xlsx("~/Google Drive/Imperial/Paeds/analysis/arc2020/df/neuroimaging_master.xlsx",
                             sheet = "patients",
                             col_names = TRUE) 
 
 neuroimaging.controls <- read_xlsx("~/Google Drive/Imperial/Paeds/analysis/arc2020/df/neuroimaging_master.xlsx",
                             sheet = "controls",
                             col_names = TRUE) 
# 
# Imperial.demo.df <- read_xlsx("~/Google Drive/Imperial/Paeds/analysis/arc2020/df/neuroimaging_master.xlsx",
#                             sheet = "demo",
#                             col_names = TRUE) 
# 
# Imperial.tbi <- read_csv("~/Google Drive/Imperial/Paeds/analysis/arc2020/df/Imperial-volume-mm3.csv")
# 
# # Recoding control that was discovered as a patient (imaging data encoded as "PTBI116", Demographics as "PTBI042")
# Imperial.tbi$Participant[Imperial.tbi$Participant=="PTBI116"] <- "PTBI042"
# # Correcting encoding inconsistancies 
# Imperial.tbi$Participant[Imperial.tbi$Participant=="PTBi004"] <- "PTBI004"
# Imperial.tbi$Participant[Imperial.tbi$Participant=="PTBi103"] <- "PTBI103"
# Imperial.tbi$Participant[Imperial.tbi$Participant=="PITB010"] <- "PTBI010"


Imperial.tbi <- read_xlsx("~/Google Drive/Imperial/Paeds/tmp_QC/QC.xlsx",
                            sheet = "imperial",
                            col_names = TRUE) 


# Combine clinical dataset sheets
Imperial.roi <- merge(Imperial.tbi, Imperial.demo.df, by = "CIF_number")

#Imperial.roi <- Imperial.roi %>% dplyr::rename(Participant = Participant.x) 
tbi.df <- Imperial.roi[ which(Imperial.roi$Group=='Patient'), ]
tbi.df$Time_since_injury__months_ <- as.numeric(tbi.df$Time_since_injury__months_)
describe(tbi.df$Time_since_injury__months_)


# Combine clinical dataset sheets
tmp.df <- rbind(neuroimaging.tbi, neuroimaging.controls) 
Imperial.df <- merge(tmp.df, Imperial.roi, by = "Participant")


# Select variables of interest and rename to match population data
imp.df <- Imperial.df %>%
  dplyr::select(Participant, Age, Group, Gender, gm, wm, spm_gm_vol, spm_wm_vol, spm_csf_vol) %>%
  dplyr::rename(sample = Group) # subject = Participant, age_year = Age,


# Calculate ICV corrected values
n=length(imp.df$Participant)
for(i in 1:n) {
  imp.df$spm.TICV[i] <- (imp.df$spm_gm_vol[i] + imp.df$spm_wm_vol[i] + imp.df$spm_csf_vol[i])
  imp.df$gm.ratio[i] <- (imp.df$gm[i]/imp.df$spm.TICV[i]) # spm_gm_vol
  imp.df$wm.ratio[i] <- (imp.df$wm[i]/imp.df$spm.TICV[i]) # spm_wm_vol
}

write.csv(imp.df, "~/Google Drive/Imperial/Paeds/tmp_QC/Imperial_volume.csv")

```
